// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using QuickCross;
using SmartLearning.Shared;

namespace SmartLearning
{
	public partial class IntroductionView : ViewBase
	{
		private IntroductionViewModel ViewModel {get{ return SmartLearningApplication.Instance.IntroductionViewModel;}}
		public IntroductionView (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			InitializeBindings (View, ViewModel);
		}

	}
}
