// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using SmartLearning.Shared;
using QuickCross;

namespace SmartLearning
{
	public partial class RandomTestView : ViewBase
	{
		private RandomTestViewModel ViewModel{ get { return SmartLearningApplication.Instance.RandomTestViewModel; } }
		public RandomTestView (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			InitializeBindings (View, ViewModel);
			MainContainer.Hidden = true;
			ViewModel.VisibleAction = () => {
				MainContainer.Hidden = (ViewModel.Count <= 0);
				NewWordTextField.ResignFirstResponder();
			};
			ViewModel.SetBadgeValueAction = () => TabBarItem.BadgeValue = (ViewModel.Count > 0) ? ViewModel.Count.ToString () : null;
			MainContainer.Hidden = true;
			ViewModel.WordMeaning = "";	
		}

	}
}
