// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using QuickCross;
using SmartLearning.Shared;

namespace SmartLearning
{
	public partial class WelcomeView : ViewBase
	{
		private WelcomeViewModel ViewModel{ get { return SmartLearningApplication.Instance.WelcomeViewModel; } }
		public WelcomeView (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			InitializeBindings (View, ViewModel);
		}
	}
}
