// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using QuickCross;
using SmartLearning.Shared;

namespace SmartLearning
{
	public partial class WordDetailView : ViewBase
	{
		private WordDetailViewModel ViewModel{get{ return SmartLearningApplication.Instance.WordDetailViewModel;}} 
		public WordDetailView (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			InitializeBindings (View, ViewModel);
			Title = ViewModel.NewWord;

			if (ViewModel.ItemList == null || ViewModel.ItemList.Count <= 1)
				NavigationItem.SetRightBarButtonItem (null, false);
			else
				NavigationItem.SetRightBarButtonItem (new UIBarButtonItem ("Next", UIBarButtonItemStyle.Done, (sender,e) => {
					ViewModel.ExecuteCommand("NextCommand");
				}), false);

			Title = "Detail";
		}
	}
}
